### ISSUE TITLE
How to display values created in the tutorial 'Publishing Data in a script'  in the UI?

### ISSUE THREAD

**Issue by dmshimself** [BrewBlox/brewblox-documentation#364]
I've set up and run through the tutorial, but I'm a bit unclear on how to display the generated data in the UI or use it in (say) a wizard.  Is there anything I should also be reading up on that tells me how to do this?

**Comment by steersbob** [comment]
Published data can be selected in Graph and Metrics widgets.

For Graphs, you may need to change the "hide after" duration a few times before the field shows up. This is an active bug in the database.

It's a good idea to explain in documentation where you can actually view the new data.

**Comment by dmshimself** [comment]
Thanks Bob - I've avoided the graph widget for the moment and just added 
a single metric to a new dashboard and used the EDIT METRICS.  The Spark 
items show up just fine, but not the sample pubscript being published by 
the tutorial script.  Is there something I need to restart or register 
in some way to get it to appear?

**Comment by steersbob** [comment]
No, new values should show up immediately. To verify, you can check the history service logs (`brewblox-ctl follow history`). These will log an "Invalid history event: {topic} {error}" message if they received your data, but couldn't deal with it.

**Comment by dmshimself** [comment]
Easy answer - after I ran a brewblox-ctl env list, I saw that the http 
port for my rig was 800 rather than 80.  Once I corrected that in the 
sample script, all was well and I instantly saw the value.

Can I use this type of external data 'sensor' within brewblox itself?  I 
have in mind using a bunch of existing ESP based temp based sensors I 
already have and use these as part of my setup to avoid running long 
lengths of cable round the house.

**Comment by steersbob** [comment]
If you create a `Temp Sensor (External)` block, you can then publish new values using either REST or MQTT.

The payload is the same for both methods:
```json
{
  "id": "Sensor Block ID",
  "serviceId": "spark-one",
  "type": "TempSensorExternal",
  "data": { "setting[degC]": 21 }
}
```

For MQTT, use the `brewcast/spark/blocks/patch` topic.

For REST, send a POST request to `{HOST}/{SERVICE}/blocks/patch`

reference docs:
- https://brewblox.netlify.app/dev/service/blocks_api.html
- https://brewblox.netlify.app/dev/reference/block_types.html

**Comment by dmshimself** [comment]
Perfect - thanks Bob
